force_sync:
  name: Force Sync
  description: Pull latest data from cloud and update internal state

ptz_360:
  name: Rotate 360 degrees
  description: Rotate 360 degrees for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

ptz_down:
  name: Look down
  description: Look down for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

ptz_up:
  name: Look up
  description: Look up for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

ptz_right:
  name: Look right
  description: Look right for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

ptz_left:
  name: Look left
  description: Look left for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

reset_alarm:
  name: Reset Alarm for Alarm Panel
  description: Reset Alarm for Alarm Panel
  target:
    entity:
      domain: alarm_control_panel
      integration: eufy_security

send_message:
  name: Send Message
  description: Send a JSON message to Web Socket
  fields:
    message:
      name: Message
      description: Raw message in JSON format
      required: true
      selector:
        text:

start_p2p_livestream:
  name: Start Live Stream over P2P
  description: Send start live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_security

start_rtsp_livestream:
  name: Start Live Stream over RTSP
  description: Send start live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_security

stop_p2p_livestream:
  name: Stop Live Stream over P2P
  description: Send stop live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_security

stop_rtsp_livestream:
  name: Stop Live Stream over RTSP
  description: Send stop live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_security

trigger_alarm:
  name: Trigger Alarm for Camera
  description: Trigger Alarm for Camera
  target:
    entity:
      domain: camera
      integration: eufy_security