force_sync:
  name: Force Sync
  description: Pull latest data from cloud and update internal state

ptz_360:
  name: Rotate 360 degrees
  description: Rotate 360 degrees for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

ptz_down:
  name: Look down
  description: Look down for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

ptz_up:
  name: Look up
  description: Look up for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

ptz_right:
  name: Look right
  description: Look right for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

ptz_left:
  name: Look left
  description: Look left for supported PTZ cameras
  target:
    entity:
      domain: camera
      integration: eufy_security

reset_alarm:
  name: Reset Alarm for Alarm Panel
  description: Reset Alarm for Alarm Panel
  target:
    entity:
      domain: alarm_control_panel
      integration: eufy_security

alarm_arm_custom1:
  name: Arm Customer 1 for Alarm Panel
  description: Arm Customer 1 for Alarm Panel
  target:
    entity:
      domain: alarm_control_panel
      integration: eufy_security

alarm_arm_custom2:
  name: Arm Customer 2 for Alarm Panel
  description: Arm Customer 2 for Alarm Panel
  target:
    entity:
      domain: alarm_control_panel
      integration: eufy_security

alarm_arm_custom3:
  name: Arm Customer 3 for Alarm Panel
  description: Arm Customer 3 for Alarm Panel
  target:
    entity:
      domain: alarm_control_panel
      integration: eufy_security

send_message:
  name: Send Message
  description: Send a JSON message to Web Socket
  fields:
    message:
      name: Message
      description: Raw message in JSON format
      required: true
      selector:
        text:

start_p2p_livestream:
  name: Start Live Stream over P2P
  description: Send start live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_security

start_rtsp_livestream:
  name: Start Live Stream over RTSP
  description: Send start live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_security

stop_p2p_livestream:
  name: Stop Live Stream over P2P
  description: Send stop live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_security

stop_rtsp_livestream:
  name: Stop Live Stream over RTSP
  description: Send stop live stream command to camera
  target:
    entity:
      domain: camera
      integration: eufy_security

trigger_camera_alarm_with_duration:
  name: Trigger Alarm for a Duration
  description: Trigger Alarm for a Duration
  target:
    entity:
      domain: camera
      integration: eufy_security
  fields:
    duration:
      name: Duration
      description: Duration in seconds
      required: true
      example: 10
      default: 10
      selector:
        number:
          min: 0
          max: 300


trigger_base_alarm_with_duration:
  name: Trigger Alarm for a Duration
  description: Trigger Alarm for a Duration
  target:
    entity:
      domain: alarm_control_panel
      integration: eufy_security
  fields:
    duration:
      name: Duration
      description: Duration in seconds
      required: true
      example: 10
      default: 10
      selector:
        number:
          min: 0
          max: 300

quick_response:
  name: Send quick response
  description: Send quick response
  target:
    entity:
      domain: camera
      integration: eufy_security
  fields:
    voice_id:
      name: Voice Id
      description: Voice ID stored in attributes
      required: true
      example: 419
      default: 419
      selector:
        number:
          min: 0
          max: 999999

snooze:
  name: Snooze Alarm
  description: Snooze Alarm for a Duration
  target:
    entity:
      integration: eufy_security
  fields:
    snooze_time:
      name: Snooze Duration
      description: Snooze Duration in seconds
      required: true
      example: 10
      default: 10
      selector:
        number:
          min: 0
          max: 1000
    snooze_chime:
      name: Will chime be snoozed?
      required: true
      example: False
      default: False
      selector:
        boolean:
    snooze_motion:
      name: Will motion notifications be snoozed?
      required: true
      example: False
      default: False
      selector:
        boolean:
    snooze_homebase:
      name: Will home base be snoozed?
      required: true
      example: False
      default: False
      selector:
        boolean: